# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:26
from __future__ import unicode_literals

from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Mobile',
            new_name='MobileNo',
        ),
    ]
